<div>
    <h2>Artikel</h2>
    <p>Ikatan Motor Indonesia (IMI) berdedikasi untuk meningkatkan keselamatan pada setiap pengguna jalan di Indonesia. IMI sebagai pilar utama olahraga otomotif di Tanah Air turut berpartisipasi dalam menyelenggarakan program kampanye aman berkendara bertajuk #3500LIVES yang baru saja diluncurkan Fédération Internationale de l’Automobile (FIA) di Paris, Perancis pada 10 Maret lalu.

    <p>Selaku Presiden FIA, Jean Todt bersama Ketua Dewan Eksekutif JCDecaux, Jean-Charles Decaux meresmikan program kampanye yang bertujuan untuk menyebarluaskan pesan tentang keselamatan berkendara tersebut. Kecelakaan lalu lintas seringkali terjadi dan menyebabkan 3.500 nyawa melayang setiap harinya di seluruh dunia, dengan kata lain, ada 1,25 juta setiap tahun. Hal inilah yang kemudian melatarbelakangi peluncuran program #3500LIVES oleh FIA.</p>

    <p>Ketua Umum IMI Pusat, Sadikin Aksa, turut berbicara terkait program ini. Ia mengatakan, “Kampanye tentang keselamatan berkendara bukan hanya perlu dilakukan sesekali, namun harus diteruskan secara berkala. Tujuan IMI kali ini adalah untuk meningkatkan awareness masyarkat Indonesia sekaligus mensosialisasikan road safety, maka dari itu kami akan mendukung program #3500LIVES yang digagas oleh FIA.”</p>

    <p>Kampanye #3500LIVES sendiri mengambil fokus pada sepuluh poin penting, yaitu mematuhi batas kecepatan kendaraan, mengecek ban, tidak diperkenankan menggunakan seluler ketika berkendara, selalu fokus ketika berkendara, menggunakan helm, berhenti ketika merasa lelah, jangan mengonsumsi alkohol, memakai sabuk pengaman, menggunakan isofix untuk kursi balita, serta menggunakan pakaian yang memantulkan cahaya. Poin-poin tersebut juga dipromosikan oleh berbagai duta FIA, seperti atlet Yohan Blake, Haile Gebrselassie, Antoine Griezmann, Vanessa Low, Rafale Nadal, Wayde van Niekerk. Ada juga nama pebalap Fernando Alonso, Felipe Massa, Marc Marquez, Nico Rosberg, penyanyi Pharrell Williams, aktris Michelle Yeoh, serta politisi Anne Hidalgo.</p>

    <p>Masyarakat Indonesia dapat ikut berpartispasi dalam mendukung kampanye #3500LIVES lewat situs www.fia.com/3500lives. Bertajuk “Sign up, stay safe, save lives”, kampanye #3500LIVES juga mengajak siapa saja untuk menandatangani persetujuan tentang sepuluh poin penting tersebut dan meminta pemerintah untuk menjadikan keselamatan berkendara sebagai prioritas utama sekaligus memperkenalkan undang-undang tentang faktor resiko kunci dalam bekendara yang harus selalu diperhatikan.</p>
</div>